### ISSUE TITLE
Decoding process load value ends up showing on encode column

### ISSUE THREAD

**Issue by Leopard1907** [Umio-Yasuno/amdgpu_top#18]
Tested software:

-  Firefox 113.0.1 with `media.ffmpeg.vaapi.enabled` in `about:config` set to true
-  mpv 0.35.1 media player with following config options in `mpv.conf`

```
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
hwdec=vaapi
```

System info:

```
Host: b650mds3h Kernel: 6.3.2-arch1-1 arch: x86_64 bits: 64
    compiler: gcc v: 13.1.1 Desktop: KDE Plasma v: 5.27.5 tk: Qt v: 5.15.9
    wm: kwin_wayland dm: SDDM Distro: EndeavourOS base: Arch Linux
Machine:
  Type: Desktop System: Gigabyte product: B650M DS3H v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: B650M DS3H v: x.x serial: <superuser required>
    UEFI: American Megatrends LLC. v: F6 date: 05/17/2023
Graphics:
  Device-1: AMD Navi 31 [Radeon RX 7900 XT/7900 XTX] vendor: Sapphire
    driver: amdgpu v: kernel arch: RDNA-3 pcie: speed: 16 GT/s lanes: 16 ports:
    active: DP-2 empty: DP-1,HDMI-A-1,HDMI-A-2 bus-ID: 03:00.0
    chip-ID: 1002:744c
  Device-2: AMD Raphael vendor: Gigabyte driver: amdgpu v: kernel
    arch: RDNA-2 pcie: speed: 16 GT/s lanes: 16 ports: active: none empty: DP-3,
    DP-4, DP-5, HDMI-A-3 bus-ID: 12:00.0 chip-ID: 1002:164e temp: 37.0 C
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.1.1
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: modesetting,radeon alternate: fbdev,vesa dri: radeonsi
    gpu: amdgpu,amdgpu display-ID: 0
  Monitor-1: DP-2 res: 2560x1440 size: N/A
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon RX 7900 XTX (gfx1100
    LLVM 15.0.7 DRM 3.52 6.3.2-arch1-1) direct-render: Yes
```

Screenshots that shows the issue:

![Screenshot_20230521_025842](https://github.com/Umio-Yasuno/amdgpu_top/assets/24878978/b4ff5cf6-0c3d-4c5f-9669-88091d499b0d)
![Screenshot_20230521_030242](https://github.com/Umio-Yasuno/amdgpu_top/assets/24878978/4bbd44a1-d328-469e-923e-7f690544d33b)

amdgpu-top version: 0.1.8
